[workspace]
members = ["crates/note_macro", "crates/music"]

[package]
name = "cubequest"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"
rustysynth = "1.3"
cpal = "0.15"
music = { path = "crates/music" }

[profile.release]
opt-level = 3
lto = true
